version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dog-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '8000:8000'
  web:
    image: node-docker
    depends_on:
      - db
    ports:
      - '4000:4000'


